### PR TITLE
Move ansible roles inside this repository

### LINKED ISSUE #18: Move the Kubernetes and docker installation roles inside this repo
[ferrarimarco.kubernetes](https://galaxy.ansible.com/ferrarimarco/kubernetes) and [ferrarimarco.docker](https://galaxy.ansible.com/ferrarimarco/docker) roles have been downloaded less than 1000 times combined, so not worth maintaining in separate repos.

### PR DESCRIPTION
**Pull request by ferrarimarco**
This PR: 

1. Moves the `ferrarimarco.kubernetes` and `ferrarimarco.docker` Ansible roles inside this repository. These roles never had a wide use, besides what we do in this repo, so moving those here will make this project easier to maintain (no need to push to ansible galaxy).
1. Configures ansible-lint to run during CI builds
1. Add preliminary support for running Test-Kitchen in CI. For now, you can run the test suite manually (see README for instructions).

- [x] Copy code inside this repo
- [x] Remove unneeded files
- [x] Edit playbooks to suit new roles
- [x] Configure CI
- [x] Add instructions in README to run the test suite
- [ ] Delete roles from Galaxy
- [ ] Delete/archive old GitHub repos

Closes #18

### CODE REVIEW

**Comment by ferrarimarco** [comment]
you can run the test suite!

**Comment by StefanoSalsano** [comment]
do you mean follow these instructions in the Readme.md ?

Running the tests
See .travis.yml for details about the linters.
If you want to run tests manually:
    Install the dependencies:
        gem install bundler
        bundle install
    Run the tests with Test-Kitchen: kitchen test

sorry I cannot understand them :-) 
they assume prior knowledge... where do I have to install the dependencies? at which phase of the deployment should I run them?  
( ti sto offrendo tutta la mia ignoranza... :-) )

**Comment by ferrarimarco** [comment]
:) There's a running tests section in the README

**Comment by StefanoSalsano** [comment]
> 
> 
> :) There's a running tests section in the README

yes, this is the one that I've reported verbatim above... but it is not enough for me to understand how to run the test, I repeat my questions:
- where do I have to install the dependencies?
- at which phase of the deployment should I run them?

**Comment by ferrarimarco** [comment]
Oh! Now I understand your questions. I'll extend it. BTW, you can run it regardless of which phase/state you're in. Test Kitchen will manage the lifecycle of the instances. The next phase (for which there's already an issue) is:

1. Run those tests against all the VMs in the cluster.
1. Extend tests to cover tasks in the `post_tasks `section.
1. Extend tests to cover other aspects of the cluster (e.g. number of running nodes, if there's any crashing pod...)

**Comment by StefanoSalsano** [comment]
I think we should clarify at high level what is the purpose and the scope of the "test", it's not explained in the README

**Comment by ferrarimarco** [comment]
@StefanoSalsano added some fixes + extended the README.

**Comment by StefanoSalsano** [comment]
the extended README is a step in the right direction, but still it is not clear to me the overall picture of running the test... maybe we can shortly discuss in a webconf and then I can help to write the documentation in a clear way... if the code part is OK I suggest to merge and I've already opened the issue #100 concerning minor improvements to the documentation, we can open a further PR to improve the doc

**Pull request merged**
