### PR TITLE
Implement a dynamic configuration mechanism

### LINKED ISSUE #8: Implement a dynamic configuration mechanism
Users should be allowed to customize the environment

### LINKED ISSUE #34: Make the cluster configuration completely dynamic
Currently the nodes of the cluster (number, type...) are hard-coded in the Vagrantfile.

We should load it from the YAML configuration file, so a user can add/remove nodes at will.

### PR DESCRIPTION
**Pull request by ferrarimarco**
This PR implements the dynamic cluster configuration.

Instead of having to manually modify the Vagrantfile when you have to change the number of nodes, you just change the desired node count.

Close #34

### CODE REVIEW

**Comment by ferrarimarco** [comment]
I started working on this. I suppose it's needed for our next steps.

@StefanoSalsano dynamically configuring worker nodes is relatively easy. If we want to support dynamic master configuration it's a bit harder, because we've to distinguish the role of the "first master" and the other masters, at least during the provisioning phase.

**Comment by StefanoSalsano** [comment]
@ferrarimarco I think we can explicitly state that we currently support only one master... and add in the (long term) roadmap the support of multiple masters... I see it as a true enhancement / new feature rather than a technical debt ;-)
and even if you consider it a technical debt, it was already included

**Comment by StefanoSalsano** [comment]
@ferrarimarco note that I was planning to improve the IPv6 numbering of nodes, the old one was:
  minion_1_ipv6_part: "c41e::"
  minion_2_ipv6_part: "c41f::"
  minion_3_ipv6_part: "c420::"

the new one should be
  minion_1_ipv6_part: "c41e::1"
  minion_2_ipv6_part: "c41f::1"
  minion_3_ipv6_part: "c420::1"
I can write some generic code to assign it...

**Comment by ferrarimarco** [comment]
Right. I can implement your logic in this PR!

**Comment by StefanoSalsano** [comment]
@ferrarimarco ok I am implementing the logic in this branch... I am working on Vagrantfile and defaults.yaml... I will push a commit in 30 min

**Comment by StefanoSalsano** [comment]
I'm also working on the IPv4 address assignment...

**Comment by ferrarimarco** [comment]
@StefanoSalsano ping!

**Pull request merged**
