### PR TITLE
Configure CI for linting

### PR DESCRIPTION
**Pull request by ferrarimarco**
This PR configures more linters to run during the CI build.

For #30

### CODE REVIEW

**Comment by ferrarimarco** [comment]
@StefanoSalsano this PR configures linters for markdown and yaml to run during our CI builds. It's working, as you can see from the logs.

I'll fix the errors, then this is PR can be reviewed.

**Comment by StefanoSalsano** [comment]
ok, but is it worth to enforce a strict constraint on line length for .yaml and .md files ?
aren't we making our lives too difficult in this specific case ? 
maybe it is possible to relax this check only?

**Comment by ferrarimarco** [comment]
For markdown is easy to comply with the rule, just add a newline :)

For YAML it's a [bit more complicated](https://yaml-multiline.info/), but I found it increases readability

**Comment by StefanoSalsano** [comment]
yes I'm worried about the YAML files, the typical case is where we have long shell commands 
for example copy/pasting from shell command line to yaml file and vice versa will become more complicated
understanding https://yaml-multiline.info/ may be an entry barrier for other contributors (not too high, but still some time to understand...)
overall, I think the productivity will decrease a bit as the complications (for example due to the time needed to submit a pull request, then discover that lint check fails and then correct and resubmit) are not recovered by the increased readability
in https://yamllint.readthedocs.io/en/stable/configuration.html it is explained how it is possible to turn the line length check into a warning or to increase the limit (e.g. up to 120)
anyway... I'll leave you to decide :-) if you really think that readability is preferable I will approve after that you have changed all yaml files

**Comment by ferrarimarco** [comment]
If fixed all the warnings. I feel readability increased and now it's easier to add parameters for long ansible tasks. WDYT?

Note that in one case I've disable yamllint line length check because the literal was not splittable, so this is still an option.

**Comment by ferrarimarco** [comment]
@StefanoSalsano ready for your review!

We currently lint and validate:

- Travis config file
- Shell scripts
- YAML files
- Markdown files
- Vagrantfile

**Pull request merged**
