### PR TITLE
Allow pods to be scheduled on master nodes, if configured

### LINKED ISSUE #203: add the option to run workloads into the master node
there exist configurations in which it is useful to deploy workloads on the master node

this is needed by SRv6-PM project (issue #204) 

the activation of this feature should be configurable with settings.yaml

### PR DESCRIPTION
**Pull request by ferrarimarco**
This PR adds a new configuration option (`kubernetes.allow_workloads_on_masters`) in `defaults.yaml` to allow scheduling Pods on master nodes.

Merge after #217.

Close #203

### CODE REVIEW

**Comment by ferrarimarco** [comment]
That's a fair question actually. We currently take care of draining worker nodes only, and then reset the master (with kubeadm). This is enough to cleanup, but if we want to support multiple masters, then we've to take care about this.

**Comment by ferrarimarco** [comment]
There's no additional cleanup needed, because we already drain and delete all the nodes.

**Comment by ferrarimarco** [comment]
@StefanoSalsano I've resolved a conflict, you need to approve again. Thanks!

**Comment by ferrarimarco** [comment]
@StefanoSalsano ping! If we merge this, we've a clean situation to start from for the other draft PRs :)

**Comment by StefanoSalsano** [comment]
sorry I cleaned up my inbox too aggressively and lost your review request :-(
doing right now!

**Pull request merged**
