### PR TITLE
Fix adding the additional disk and the loop on WSL by switching to triggers

### LINKED ISSUE #98: The additional disk cannot be created in WSL
The mechanism we're currently using to create an additional disk doesn't work if you run Vagrant in WSL, because the Virtualbox provisioner (that is installed on Windows) uses Windows paths.

```shell
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["createmedium", "disk", "--filename", "/mnt/c/Users/XXXXX/workspaces/kubernetes-playground/base-box-builder.k8s-play.local-disk-2.vmdk", "--size", "10240", "--format", "VMDK"]

Stderr: 0%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage.exe: error: Failed to create medium
VBoxManage.exe: error: Could not create the medium storage unit 'C:\mnt\c\Users\XXXXX\workspaces\kubernetes-playground\base-box-builder.k8s-play.local-disk-2.vmdk'.
VBoxManage.exe: error: VMDK: could not create new file 'C:\mnt\c\Users\XXXXX\workspaces\kubernetes-playground\base-box-builder.k8s-play.local-disk-2.vmdk' (VERR_ALREADY_EXISTS)
VBoxManage.exe: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component MediumWrap, interface IMedium
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreateMedium(struct HandlerArg *)" at line 510 of file VBoxManageDisk.cpp
```

### LINKED ISSUE #181: Vagrant is stuck in a loop under WSL
The class `SetName` and `Destroy` extensions we wrote to attach an additional disk are called in a loop under WSL.

This makes the system unusable under WSL.

I encountered this issue while working on #98

### PR DESCRIPTION
**Pull request by ferrarimarco**
This PR fixes multiple WSL issues, and start using Vagrant triggers to also fix #181 (and I already proposed to do so in #127, so three issues closes in a single PR!).

While working on this, I've also implemented:

- A check to verify that shell scripts are executable.
- Generation of an `env.yaml` for Travis CI.

Close #98, #127, #181

### CODE REVIEW

**Comment by ferrarimarco** [comment]
I'm marking this as a draft again. After an early evaluation, I concluded that if we switch to Vagrant triggers (as we propose in #127), we can fix both #98 and #181.

**Comment by ferrarimarco** [comment]
@StefanoSalsano @zvfvrv @simonezacca can you please test this PR in your environments?

So far, I've tested:

- Virtualbox on Windows
- Virtualbox on WSL


@simonezacca can you test Virtualbox on macOS?

@zvfvrv I didn't touch the libvirt part, but we still don't test the vagrant part in Travis, so can you have a look as well? Thanks!

**Comment by StefanoSalsano** [comment]
> @StefanoSalsano @zvfvrv @simonezacca can you please test this PR in your environments?
> So far, I've tested:
>     * Virtualbox on Windows
>     * Virtualbox on WSL
> 
> @StefanoSalsano do you have a "Virtualbox on linux" environment somewhere?

@ferrarimarco no, I can only test again Virtualbox on Windows sorry!

**Comment by zvfvrv** [comment]
Hi @ferrarimarco , just tested with Virtualbox on Linux and it work fine

**Pull request merged**
