### PR TITLE
fix cleanup script

### PR DESCRIPTION
**Pull request by StefanoSalsano**
the cleanup script run by Vagrant file is not ok because it should be run as vagrant user

now Vagrantfile calls launch-cleanup.sh and launch-cleanup.sh runs  cleanup-k8s-and-cni.sh as vagrant user

### CODE REVIEW

**Comment by StefanoSalsano** [comment]
closes issue #69

**Comment by ferrarimarco** [comment]
@StefanoSalsano added a couple of commits, LMK what you think :)

**Comment by StefanoSalsano** [comment]
ok the proposed solution wanted to avoid hardcoding the /home/vagrant path, this is also why the script was needed to be run as vagrant and then with sudo inside.
but it is ok to go as you propose, also because I realized that what you propose is symmetric with what happens in bootstrap-kubernetes-master.sh, in which the /home/vagrant path is hardcoded and the script is run as root
I will now fix a minor issue introduce by your commit and then I think we are ready

**Comment by ferrarimarco** [comment]
Great, thanks.

I'll open a new issue to track the hardcoded path :)

**Comment by StefanoSalsano** [comment]
I think you have removed by mistake  scripts/linux/install-kubernetes.sh in commit https://github.com/ferrarimarco/kubernetes-playground/pull/68/commits/53fdfc24868b3e64907de147e6058d8781eca69f

I am restoring it :-)

**Comment by StefanoSalsano** [comment]
the fact that the file is removed in https://github.com/ferrarimarco/kubernetes-playground/commit/53fdfc24868b3e64907de147e6058d8781eca69f and then restored in my commit https://github.com/ferrarimarco/kubernetes-playground/pull/68/commits/34d9bbd0aa16216472137d590de0a9fa0027bf3b is not good when doing the merge in other branches :-( ... to continue my work I am creating a new branch ok-fix-cleanup-script
in which I am applying only the final changes

**Comment by StefanoSalsano** [comment]
FYI I have created the branch ok-fix-cleanup-script which is the clean version of this branch

**Pull request merged**
